# Generated by Django 3.1.2 on 2020-10-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201015_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='donated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
