# Generated by Django 3.1.2 on 2021-01-21 08:27

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201128_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default='foo@gmail.com', max_length=300),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='foo', max_length=300),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=django_quill.fields.QuillField(),
        ),
    ]
