# Generated by Django 3.1.2 on 2020-10-16 14:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201016_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='donor_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DonationTransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_donated', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('donor_name', models.CharField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('cause', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cause')),
            ],
        ),
    ]
