# Generated by Django 3.1.2 on 2020-11-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201121_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='block_quote',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
